version: "3.5"

services:
  web:
    build: .
    command: uvicorn main:app --reload --host "0.0.0.0" --port 5000
    volumes:
    - .:/opt/www/app
    ports:
    - 5000:5000

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
